GourmetRestaurantWeb/Controllers/OrderController.cs
using GourmetRestaurant.DataAccess.Data;
using GourmetRestaurant.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GourmetRestaurantWeb.Controllers
{
	[Route("api/[controller]")]
	[ApiController]
	public class OrderController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;

		public OrderController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
			_unitOfWork = unitOfWork;
		}

		[HttpGet]
		[Authorize]
        public IActionResult Get()
		{
			var OrderHeaderList = _unitOfWork.OrderHeader.GetAll(includeProperties:"ApplicationUser");
			return Json(new {data = OrderHeaderList});
		}

	}
}

GourmetRestaurantWeb/Pages/Admin/Order/ManageOrder.cshtml.cs
using GourmetRestaurant.DataAccess.Repository.IRepository;
using GourmetRestaurant.Models;
using GourmetRestaurant.Models.ViewModel;
using GourmetRestaurant.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GourmetRestaurantWeb.Pages.Admin.Order
{
    [Authorize(Roles = $"{SD.KitchenRole},{SD.ManagerRole}")]
    public class ManageOrderModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public List<OrderDetailVM> OrderDetailVM { get; set; }
        public ManageOrderModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public void OnGet()
        {
            //populate orderdetailvm
            OrderDetailVM = new();

            List<OrderHeader> orderHeaders = _unitOfWork.OrderHeader.GetAll(u => u.Status == SD.StatusSubmitted ||
            u.Status == SD.StatusInProcess).ToList();

            foreach(OrderHeader item in orderHeaders)
            {
                OrderDetailVM individual = new OrderDetailVM()
                {
                    OrderHeader = item,
                    OrderDetails = _unitOfWork.OrderDetails.GetAll(u => u.OrderId == item.Id).ToList()
                };
                OrderDetailVM.Add(individual);
            }
        }
        //manage order buttons
        public IActionResult OnPostOrderInProcess(int orderId)
        {
            _unitOfWork.OrderHeader.UpdateStatus(orderId, SD.StatusInProcess);
            _unitOfWork.Save();
            return RedirectToPage("ManageOrder");
        }
        //manage order buttons
        public IActionResult OnPostOrderReady(int orderId)
        {
            _unitOfWork.OrderHeader.UpdateStatus(orderId, SD.StatusReady);
            _unitOfWork.Save();
            return RedirectToPage("ManageOrder");
        }
        //manage order buttons
        public IActionResult OnPostOrderCancel(int orderId)
        {
            _unitOfWork.OrderHeader.UpdateStatus(orderId, SD.StatusCancelled);
            _unitOfWork.Save();
            return RedirectToPage("ManageOrder");
        }
    }
}

GourmetRestaurantWeb/Pages/Admin/Order/OrderDetails.cshtml.cs
using GourmetRestaurant.DataAccess.Repository.IRepository;
using GourmetRestaurant.Models;
using GourmetRestaurant.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GourmetRestaurantWeb.Pages.Admin.Order
{
    public class OrderDetailsModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public OrderDetailVM OrderDetailVM { get; set; }
        public OrderDetailsModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        public void OnGet(int id)
        {
            OrderDetailVM = new()
            {
                OrderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(u => u.Id == id, includeProperties: "ApplicationUser"),
                OrderDetails = _unitOfWork.OrderDetails.GetAll(u => u.OrderId == id).ToList(),
            };
        }
    }
}

GourmetRestaurantWeb/Pages/Admin/Order/OrderList.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GourmetRestaurantWeb.Pages.Admin.Order
{
    [Authorize]
    public class OrderListModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

GourmetRestaurantWeb/Pages/Admin/Order/ManageOrder.cshtml
@page
@model GourmetRestaurantWeb.Pages.Admin.Order.ManageOrderModel
@using GourmetRestaurant.Utility

<h1 class="text-primary py-3">Manage Order's</h1>
<form method="post">
    <div class="container row bg-white p-2 mb-3 rounded">
        @foreach(var item in Model.OrderDetailVM){
        <div class="col-12 pb-3 pt-3 mt-4 border  rounded">
            <div class="row">
                <div class="col-4">
                    Order Number : @item.OrderHeader.Id
                    <ul class="text-info">
                        @foreach(var details in item.OrderDetails){
                        <li>@details.Name x @details.Count</li>
                        }
                    </ul>
                </div>
                <div class="col-4 pb-2">
                    <div class="input-group pb-2">
                        <div class="input-group-append">
                            <span class="input-group-text bg-secondary border">Time</span>
                        </div>
                        <input type="text" value="@item.OrderHeader.PickUpTime" class="form-control" readonly />
                    </div>
                    <textarea readonly asp-for="@item.OrderHeader.Comments" class="rounded border form-control" rows="3"></textarea>
                </div>
                <div class="col-3 offset-1 d-flex align-content-center">
                    <div class="col-12">

                        @if (item.OrderHeader.Status == SD.StatusSubmitted) {
                        <button type="submit" class="btn btn-primary form-control mb-3"
                                asp-page-handler="OrderInProcess" asp-route-orderId="@item.OrderHeader.Id">
                            <i class="bi bi-check-square"></i> &nbsp; Start Cooking
                        </button>
                        }
                            @if (item.OrderHeader.Status == SD.StatusInProcess) { 
                        <button type="submit" class="btn btn-success form-control mb-3"
                                asp-page-handler="OrderReady" asp-route-orderId="@item.OrderHeader.Id">
                            <i class="bi bi-emoji-laughing"></i> &nbsp; Order Ready
                        </button>
                        }
                        
                        <button type="submit" class="btn btn-warning form-control mb-3"
                                asp-page-handler="OrderCancel" asp-route-orderId="@item.OrderHeader.Id">
                            <i class="bi bi-x-square-fill"></i> &nbsp; Cancel Order
                        </button>
                        
                    </div>
                </div>
            </div>
        </div>
        }
    </div>

</form>

GourmetRestaurantWeb/Pages/Admin/Order/OrderDetails.cshtml
@page
@model GourmetRestaurantWeb.Pages.Admin.Order.OrderDetailsModel

<form method="post">
    <div class="border p-4 ml-1 backgroundWhite mt-4">
        <div class="row pb-1">
            <div class="col-12 col-md-6 ">
                <p class="h2  text-primary">Order Details</p>
            </div>
            <div class="col-12 col-md-4 offset-md-2">
                <a asp-page="/Admin/Order/OrderList" class="btn btn-outline-primary form-control">Back to Orders </a>
            </div>
        </div>
        <hr />

        <div class="row pt-2">

            <div class="col-lg-8 col-12" style="border-right:1px solid #bbb9b9">

                <div class="form-group row py-1">
                    <div class="col-md-3 col-12 text-primary">
                        Name
                    </div>
                    <div class="col-md-9 col-12">
                        <input asp-for="OrderDetailVM.OrderHeader.PickupName" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row py-1">
                    <div class="col-md-3 col-12 text-primary">
                        Email
                    </div>
                    <div class="col-md-9 col-12">
                        <input asp-for="OrderDetailVM.OrderHeader.ApplicationUser.Email" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row py-1">
                    <div class="col-md-3 col-12 text-primary">
                        Phone Number
                    </div>
                    <div class="col-md-9 col-12">
                        <input asp-for="OrderDetailVM.OrderHeader.PhoneNumber" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row py-1">
                    <div class="col-md-3 col-12 text-primary">
                        Order Total
                    </div>
                    <div class="col-md-9 col-12">
                        <input asp-for="OrderDetailVM.OrderHeader.OrderTotal" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row py-1">
                    <div class="col-md-3 col-12 text-primary">
                        Order Pickup Date Time
                    </div>
                    <div class="col-md-9 col-12">
                        <input value="@Model.OrderDetailVM.OrderHeader.PickUpTime.ToShortDateString() @Model.OrderDetailVM.OrderHeader.PickUpTime.ToShortTimeString()" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row py-1">
                    <div class="col-md-3 col-12 text-primary">
                        Comments
                    </div>
                    <div class="col-md-9 col-12">
                        <textarea asp-for="OrderDetailVM.OrderHeader.Comments" disabled class="form-control" rows="3"></textarea>
                    </div>
                </div>

            </div>

            <div class="col-lg-4 col-12">
                <h4 class="d-flex justify-content-between align-content-center mb-3">
                    <span class="text-muted">Order ID: </span>
                    <span class="badge badge-secondary badge-pill">@Model.OrderDetailVM.OrderHeader.Id</span>
                </h4>
                <ul class="list-group mb-3">
                    @foreach(var detail in Model.OrderDetailVM.OrderDetails) {
                    <li class="list-group-item d-flex justify-content-between">
                        <div>
                            <h6 class="my-0">@detail.Name</h6>
                            <small class="text-muted">Quantity : @detail.Count</small>
                        </div>
                        <span class="text-muted">$@(detail.Price * detail.Count)</span>
                    </li>
                    }

                    <li class="list-group-item d-flex justify-content-between bg-light">
                        <span class="text-info"> Total (USD)</span>
                        <strong class="text-info">$@Model.OrderDetailVM.OrderHeader.OrderTotal</strong>
                    </li>

                </ul>

                <button type="submit" disabled class="btn btn-info form-control">ORDER STATUS</button>


                <div class="row pt-3">
                    <div class="col-6">
                        <button type="submit" class="btn btn-warning form-control"><i class="bi bi-x-square"></i> Cancel Order</button>
                    </div>
                    <div class="col-6">
                        <button type="submit" class="btn btn-danger form-control"><i class="bi bi-currency-dollar"></i> Refund Order</button>
                    </div>
                </div>



            </div>

        </div>
    </div>
</form>

GourmetRestaurantWeb/Pages/Admin/Order/OrderList.cshtml
@page
@model GourmetRestaurantWeb.Pages.Admin.Order.OrderListModel

<div class="container p-3">
	<div class="row pt-4">
		<div class="col-6">
			<h2 class="text-primary">Order List</h2>
		</div>
		<div class="col-6 text-end">
		</div>
	</div>
	<br />

	<table id="DT_Load" class="table table-striped table-bordered" style="text-align:center">
		<thead>
			<tr>
				<th style="text-align:center">Order ID</th>
				<th style="text-align:center">Name</th>
				<th style="text-align:center">Email</th>
				<th style="text-align:center">Order Total</th>
				<th id="date" style="text-align:center">Pickup Time</th>
				<th></th>
			</tr>
		</thead>
	</table>
</div>

@section Scripts
	{
	<script src="~/js/orderList.js"></script>
}