GourmetRestaurantWeb/Pages/Customer/Cart/Index.cshtml.cs
using GourmetRestaurant.DataAccess.Repository.IRepository;
using GourmetRestaurant.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace GourmetRestaurantWeb.Pages.Customer.Cart
{
    [Authorize]
    public class IndexModel : PageModel
    {
        public IEnumerable<ShoppingCart> ShoppingCartList { get; set; }

        public double CartTotal { get; set; }

        private readonly IUnitOfWork _unitOfWork;

        public IndexModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            CartTotal = 0;
        }
        public void OnGet()
        {
            //retrieve user id of the logged in user, after we get the complete list of shoppingcart list
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if(claim != null)
            {
                ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(filter: u => u.ApplicationUserId == claim.Value,
                    includeProperties:"MenuItem,MenuItem.FoodType,MenuItem.Category");
            }

            foreach(var CartItem in ShoppingCartList)
            {
                CartTotal += (CartItem.MenuItem.Price * CartItem.Count);
            }
        }
        //Plus --> asp-page-handler name, cartId --> asp-route-(CartId)
        public IActionResult OnPostPlus(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(u => u.Id == cartId);
            _unitOfWork.ShoppingCart.IncrementCount(cart, 1);
            return RedirectToPage("/Customer/Cart/Index");
        }

        public IActionResult OnPostMinus(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(u => u.Id == cartId);
            if(cart.Count == 1)
            {
                _unitOfWork.ShoppingCart.Remove(cart);
                _unitOfWork.Save();
            }
            else
            {
                _unitOfWork.ShoppingCart.DecrementCount(cart, 1);
            }
            return RedirectToPage("/Customer/Cart/Index");
        }

        public IActionResult OnPostRemove(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(u => u.Id == cartId);
            _unitOfWork.ShoppingCart.Remove(cart);
            _unitOfWork.Save();
            return RedirectToPage("/Customer/Cart/Index");
        }
    }
}

GourmetRestaurantWeb/Pages/Customer/Cart/OrderConfirmation.cshtml.cs
using GourmetRestaurant.DataAccess.Repository.IRepository;
using GourmetRestaurant.Models;
using GourmetRestaurant.Utility;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Stripe.Checkout;

namespace GourmetRestaurantWeb.Pages.Customer.Cart
{
	public class OrderConfirmationModel : PageModel
	{
		private readonly IUnitOfWork _unitOfWork;
		public int OrderId { get; set; }
		public OrderConfirmationModel(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}
		public void OnGet(int id)
		{
			OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(u => u.Id == id);
			if (orderHeader.SessionId != null)
			{
				var service = new SessionService();
				Session session = service.Get(orderHeader.SessionId);
				if (session.PaymentStatus.ToLower() == "paid")
				{
					orderHeader.Status = SD.StatusSubmitted;
					_unitOfWork.Save();
				}
			}
			List<ShoppingCart> shoppingCarts =
				_unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == orderHeader.UserId).ToList();
			_unitOfWork.ShoppingCart.RemoveRange(shoppingCarts);
			_unitOfWork.Save();
			OrderId = id;
		}
	}
}

GourmetRestaurantWeb/Pages/Customer/Cart/Summary.cshtml.cs
using GourmetRestaurant.DataAccess.Repository.IRepository;
using GourmetRestaurant.Models;
using GourmetRestaurant.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Stripe.Checkout;
using System.Net.NetworkInformation;
using System.Security.Claims;

namespace GourmetRestaurantWeb.Pages.Customer.Cart
{
	[Authorize]
	[BindProperties]
	public class SummaryModel : PageModel
	{
		public IEnumerable<ShoppingCart> ShoppingCartList { get; set; }

		public OrderHeader OrderHeader { get; set; }

		private readonly IUnitOfWork _unitOfWork;

		public SummaryModel(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
			OrderHeader = new OrderHeader();
		}
		public void OnGet()
		{
			//retrieve user id of the logged in user, after we get the complete list of shoppingcart list
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

			if (claim != null)
			{
				ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(filter: u => u.ApplicationUserId == claim.Value,
					includeProperties: "MenuItem,MenuItem.FoodType,MenuItem.Category");
			}

			foreach (var CartItem in ShoppingCartList)
			{
				OrderHeader.OrderTotal += (CartItem.MenuItem.Price * CartItem.Count);
			}
			ApplicationUser applicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == claim.Value);
			OrderHeader.PickupName = applicationUser.FirstName + " " + applicationUser.LastName;
			OrderHeader.PhoneNumber = applicationUser.PhoneNumber;
		}

		public IActionResult OnPost()
		{
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
			if (claim != null)
			{
				ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(filter: u => u.ApplicationUserId == claim.Value,
					includeProperties: "MenuItem,MenuItem.FoodType,MenuItem.Category");

				foreach (var cartItem in ShoppingCartList)
				{
					OrderHeader.OrderTotal += (cartItem.MenuItem.Price * cartItem.Count);
				}

				OrderHeader.Status = SD.StatusPending;
				OrderHeader.OrderDate = System.DateTime.Now;
				OrderHeader.UserId = claim.Value;
				OrderHeader.PickUpTime = Convert.ToDateTime(OrderHeader.PickUpDate.ToShortDateString() + " " +
					OrderHeader.PickUpTime.ToShortTimeString());
				_unitOfWork.OrderHeader.Add(OrderHeader);
				_unitOfWork.Save();

				foreach (var item in ShoppingCartList)
				{
					OrderDetails orderDetails = new()
					{
						MenuItemId = item.MenuItemId,
						OrderId = OrderHeader.Id,
						Name = item.MenuItem.Name,
						Price = item.MenuItem.Price,
						Count = item.Count
					};
					_unitOfWork.OrderDetails.Add(orderDetails);

				}
				//stripe quantity
				//_unitOfWork.ShoppingCart.RemoveRange(ShoppingCartList);
				_unitOfWork.Save();



				var domain = "https://localhost:44372/";
				var options = new SessionCreateOptions
				{
					LineItems = new List<SessionLineItemOptions>()
				,
					Mode = "payment",
					SuccessUrl = domain + $"Customer/Cart/OrderConfirmation?id={OrderHeader.Id}",
					CancelUrl = domain + "Customer/Cart/Index",
                };

                //add line items
				foreach(var item in ShoppingCartList)
				{
					var sessionLineItem = new SessionLineItemOptions
					{
						// modifying
						PriceData = new SessionLineItemPriceDataOptions
						{
							//7.99->799
							UnitAmount = (long)(item.MenuItem.Price * 100),
							Currency = "usd",
							ProductData = new SessionLineItemPriceDataProductDataOptions
							{
								Name = item.MenuItem.Name
							},
						},
						Quantity = item.Count
					};
					options.LineItems.Add(sessionLineItem);
                }
                

                var service = new SessionService();
				Session session = service.Create(options);
				Response.Headers.Add("Location", session.Url);

				OrderHeader.SessionId = session.Id;
				OrderHeader.PaymentIntentId = session.PaymentIntentId;
				_unitOfWork.Save();
				return new StatusCodeResult(303);
			}

			return Page();
		}

	}
}

GourmetRestaurantWeb/Pages/Customer/Home/Details.cshtml.cs
using GourmetRestaurant.DataAccess.Repository.IRepository;
using GourmetRestaurant.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace GourmetRestaurantWeb.Pages.Customer.Home
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public DetailsModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [BindProperty]
        public ShoppingCart ShoppingCart { get; set; }

        public void OnGet(int id)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
           
            ShoppingCart = new()
            {
                ApplicationUserId = claim.Value,
                MenuItem = _unitOfWork.MenuItem.GetFirstOrDefault(u => u.Id == id, includeProperties: "Category,FoodType"),
                MenuItemId = id
            };
        }

        public IActionResult OnPost()
        {
            //always need validation when we post anything
            if(ModelState.IsValid)
            {
                ShoppingCart shoppingCartFromDb = _unitOfWork.ShoppingCart.GetFirstOrDefault(
                    filter: u => u.ApplicationUserId == ShoppingCart.ApplicationUserId &&
                    u.MenuItemId == ShoppingCart.MenuItemId);

                if(shoppingCartFromDb == null)
                {
                    _unitOfWork.ShoppingCart.Add(ShoppingCart);
                    _unitOfWork.Save();
                }
                else
                {
                    _unitOfWork.ShoppingCart.IncrementCount(shoppingCartFromDb, ShoppingCart.Count);
                }
                return RedirectToPage("Index");
            }
            return Page();
        }
    }
}

GourmetRestaurantWeb/Pages/Customer/Home/Index.cshtml.cs
using GourmetRestaurant.DataAccess.Repository.IRepository;
using GourmetRestaurant.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GourmetRestaurantWeb.Pages.Customer.Home
{
    public class IndexModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public IndexModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IEnumerable<MenuItem> MenuItemList { get; set; }
		public IEnumerable<Category> CategoryList { get; set; }

		public void OnGet()
        {
            MenuItemList = _unitOfWork.MenuItem.GetAll(includeProperties: "Category,FoodType");
            CategoryList = _unitOfWork.Category.GetAll(orderby: u=>u.OrderBy(c=>c.DisplayOrder));
        }
    }
}

GourmetRestaurantWeb/Pages/Customer/Cart/Index.cshtml
@page
@model GourmetRestaurantWeb.Pages.Customer.Cart.IndexModel


<form method="post">
    <br />
    @if(Model.ShoppingCartList.Count()==0)
    {
        <div>
            Please add items to the shopping cart.
        </div>
    }
    else {
    <div class="container">
        <div class="card">
            <div class="card-header bg-dark text-light ml-0 ">
                <div class="row">
                    <div class="col-6 pt-2">
                        Shopping Cart
                    </div>
                    <div class="col-6 text-end">
                        <a href="~/Customer/Home/Index" class="btn btn-outline-info btn-sm">Continue Shopping</a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                @foreach(var item in Model.ShoppingCartList) {
                <div class="row">
                    <div class="d-none d-lg-block col-lg-2 text-center py-2">
                        <img src="@item.MenuItem.Image" class="rounded" width="120" height="80" />
                    </div>
                    <div class="col-12 text-sm-center text-md-start col-md-5 pt-md-4 ">
                        <h4><strong>@item.MenuItem.Name</strong></h4>

                        <div class="badge bg-primary text-center" style="font-size:12px;">
                            @item.MenuItem.Category.Name
                        </div>
                        <div class="badge bg-info text-center" style="font-size:12px;">
                            @item.MenuItem.FoodType.Name
                        </div>
                    </div>
                    <div class="col-12 text-sm-center col-md-5 text-md-start row pt-3">
                        <div class="col-4 text-md-right pt-md-3" style="padding-top:5px;">
                            <h6><strong>$@item.MenuItem.Price <span class="text-muted">x</span> @item.Count </strong></h6>
                        </div>
                        <div class="col-6 col-sm-4 col-lg-6">
                            <button type="submit" class="btn btn-primary"
                            asp-page-handler="plus" asp-route-cartId="@item.Id">
                                <i class="bi bi-plus-square"></i>
                            </button>
                            <button type="submit" class="btn btn-danger"
                            asp-page-handler="minus" asp-route-cartId="@item.Id">
                                <i class="bi bi-dash-square"></i>
                            </button>
                        </div>
                        <div class="col-2 col-sm-4 col-lg-2 text-right">
                            <button type="submit" class="btn btn-outline-danger"
                            asp-page-handler="remove" asp-route-cartId="@item.Id">
                                <i class="bi bi-trash-fill"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <hr />
                }

                <div class="row">
                    <div class="col-12 col-md-5">
                    </div>
                    <div class="col-12 col-md-6 offset-md-1 col-lg-4 offset-lg-3 pr-4">
                        <ul class="list-group">
                            <li class="list-group-item d-flex justify-content-between bg-light">
                                <span class="text-info"> Total (USD)</span>
                                    <strong class="text-info">$@Model.CartTotal.ToString("0.00")</strong>
                            </li>
                        </ul>
                    </div>
                </div>


            </div>
            <div class="card-footer">
                <div class="col-12 col-lg-4 offset-lg-8 col-md-6 offset-md-6">
                    <a asp-page="Summary" class="btn btn-success form-control">Summary</a>
                </div>
            </div>
        </div>
    </div>
    }
</form>

GourmetRestaurantWeb/Pages/Customer/Cart/OrderConfirmation.cshtml
@page
@model GourmetRestaurantWeb.Pages.Customer.Cart.OrderConfirmationModel


<div class="container row">
    <div class="col-12 text-center">
        <h1 class="text-primary text-center">Order Placed Successfully!</h1>
        Your Order Number is : @Model.OrderId <br /><br />
        <img src="~/images/lawn_leaf.jpg" width="65%" />
    </div>
    <div class="col-12 text-center" style="color:maroon">
        <br />
        Your order has been placed successfully! <br />
        Please make sure to arrive on time for hot delicious food!
    </div>
</div> 

GourmetRestaurantWeb/Pages/Customer/Cart/Summary.cshtml
@page
@using Microsoft.Extensions.Options;
@model GourmetRestaurantWeb.Pages.Customer.Cart.SummaryModel
@inject IOptions<GourmetRestaurant.Utility.StripeSettings> Stripe
<form method="post">
	<br />
	<div class="backgroundWhiteBorder">
		<div class="container">
			<div class="card">
				<div class="card-header bg-dark text-light ml-0 ">
					<div class="row">
						<div class="col-6 pt-2">
							<h3 class="text-white-50">Order Summary</h3>
						</div>
						<div class="col-6 text-end">
							<a asp-page="Index" class="btn btn-outline-info btn-sm">Back to Cart</a>
						</div>
					</div>
				</div>
				<div class="card-body">
					<div class="container rounded p-2">
						<div class="row">
							<div class="col-12 col-lg-6 pb-4">
								<div class="row">
									<h4 class="d-flex justify-content-between align-items-center mb-3">
										<span class="text-info">PickUp Details:</span>
									</h4>
								</div>
								<div class="row my-1">
									<div class="col-3">
										<label>Name</label>
									</div>
									<div class="col-9">
										<input asp-for="OrderHeader.PickupName" class="form-control" />
										<span asp-validation-for="OrderHeader.PickupName" class="text-danger"></span>
									</div>
								</div>
								<div class="row my-1">
									<div class="col-3">
										<label>Phone Number</label>
									</div>
									<div class="col-9">
										<input asp-for="OrderHeader.PhoneNumber" class="form-control" />
										<span asp-validation-for="OrderHeader.PhoneNumber" class="text-danger"></span>
									</div>
								</div>
								<div class="row my-1">
									<div class="col-3">
										<label>Pickup Date</label>
									</div>
									<div class="col-9">
										<input value="" asp-for="OrderHeader.PickUpDate" type="date" class="form-control" />
										<span asp-validation-for="OrderHeader.PickUpDate" class="text-danger"></span>
									</div>
								</div>
								<div class="row my-1">
									<div class="col-3">
										<label>Pickup Time</label>
									</div>
									<div class="col-9">
										<input value="" asp-for="OrderHeader.PickUpTime" type="time" class="form-control" />
										<span asp-validation-for="OrderHeader.PickUpTime" class="text-danger"></span>
									</div>
								</div>
								<div class="row my-1">
									<div class="col-3">
										<label>Additional Instructions: </label>
									</div>
									<div class="col-9">
										<textarea asp-for="OrderHeader.Comments" style="height:100px;" class="form-control"></textarea>
									</div>
								</div>
							</div>

							<div class="col-12 col-lg-5 offset-lg-1">
								<h4 class="d-flex justify-content-between align-items-center mb-3">
									<span class="text-info">Order Summary:</span>
								</h4>
								<ul class="list-group mb-3">
									@foreach(var detail in Model.ShoppingCartList) {
									<li class="list-group-item d-flex justify-content-between">
										<div>
											<h6 class="my-0">@detail.MenuItem.Name</h6>
											<small class="text-muted">Quantity: @detail.Count</small>
										</div>
										<span class="text-muted">$@(detail.MenuItem.Price * @detail.Count)</span>
									</li>
									}
									<li class="list-group-item d-flex justify-content-between bg-light">
										<small class="text-info">Total (USD)</small>
										<strong class="text-info">$@Model.OrderHeader.OrderTotal.ToString("0.00")</strong>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="card-footer">
					<div class="row">
						<div class="col-12 col-md-4 offset-md-8">
							<button type="submit" id="btnPlaceOrder" value="Place Order" class="btn btn-success form-control">Place Order</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>

@section Scripts {
	@{
		<script src="https://js.stripe.com/v3/"></script>
		<partial name="_ValidationScriptsPartial"></partial>
	}
}